{% set name = "jupyterlite-xeus-python" %}
{% set version = "0.9.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7f3262803f8c58280e7ba4069337471f23ad08518fcb6ef4f3abe97a3c1a79ff

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - jupyterlite-xeus-python-build = jupyterlite_xeus_python.build:start

requirements:
  host:
    - python >=3.8
    - pip
    - jupyter_packaging >=0.10,<2
    - jupyterlab >=3,<4
    - empack >=3.1,<4
  run:
    - python >=3.8
    - traitlets
    - jupyterlite-core >=0.1.0,<0.3
    - requests
    - empack >=3.1,<4
    - typer

test:
  imports:
    - jupyterlite_xeus_python
  requires:
    - pip
  commands:
    - pip check
    - test -f ${PREFIX}/share/jupyter/labextensions/@jupyterlite/xeus-python-kernel/package.json                            # [unix]
    - if not exist %PREFIX%\\share\\jupyter\\labextensions\\@jupyterlite/xeus-python-kernel\\package.json (exit 1)          # [win]

about:
  home: https://github.com/jupyterlite/xeus-python-kernel
  summary: The xeus-python Python kernel for JupyterLite running in the browser
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://xeus-python-kernel.readthedocs.io
  dev_url: https://github.com/jupyterlite/xeus-python-kernel

extra:
  recipe-maintainers:
    - DerThorsten
    - martinRenou
